# Generated by Django 4.2.7 on 2025-05-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("experience_years", models.IntegerField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("day", "Day Shift"),
                            ("night", "Night Shift"),
                            ("rotating", "Rotating"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NursePatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("shift_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nurse_service_app.nurse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("vital_signs", "Vital Signs Check"),
                            ("medication", "Medication Administration"),
                            ("wound_care", "Wound Care"),
                            ("patient_education", "Patient Education"),
                            ("assistance", "Patient Assistance"),
                            ("monitoring", "Patient Monitoring"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nurse_service_app.nurse",
                    ),
                ),
            ],
        ),
    ]
