version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  user_service:
    build: ./user_service
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  patient_service:
    build: ./patient_service
    ports:
      - "8002:8000"
    depends_on:
      - postgres

  doctor_service:
    build: ./doctor_service
    ports:
      - "8003:8000"
    depends_on:
      - postgres

  nurse_service:
    build: ./nurse_service
    ports:
      - "8004:8000"
    depends_on:
      - postgres

  appointment_service:
    build: ./appointment_service
    ports:
      - "8005:8000"
    depends_on:
      - postgres

  health_record_service:
    build: ./health_record_service
    ports:
      - "8006:8000"
    depends_on:
      - postgres

  medication_service:
    build: ./medication_service
    ports:
      - "8007:8000"
    depends_on:
      - postgres

  laboratory_service:
    build: ./laboratory_service
    ports:
      - "8008:8000"
    depends_on:
      - postgres

  pharmacy_service:
    build: ./pharmacy_service
    ports:
      - "8009:8000"
    depends_on:
      - postgres

  invoice_service:
    build: ./invoice_service
    ports:
      - "8010:8000"
    depends_on:
      - postgres

  payment_service:
    build: ./payment_service
    ports:
      - "8011:8000"
    depends_on:
      - postgres

  notification_service:
    build: ./notification_service
    ports:
      - "8012:8000"
    depends_on:
      - postgres

  insurance_service:
    build: ./insurance_service
    ports:
      - "8013:8000"
    depends_on:
      - postgres

  chatbot_service:
    build: ./chatbot_service
    ports:
      - "8014:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
