# Generated by Django 4.2.7 on 2025-05-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                ("doctor_id", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("collected", "Sample Collected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                ("sample_type", models.CharField(max_length=50)),
                ("reference_range", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technician_id", models.IntegerField()),
                ("result_value", models.TextField()),
                ("unit", models.CharField(max_length=20)),
                ("reference_range", models.CharField(max_length=100)),
                ("abnormal_flag", models.CharField(blank=True, max_length=10)),
                ("comments", models.TextField(blank=True)),
                ("result_date", models.DateTimeField(auto_now_add=True)),
                ("verified_by", models.IntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lab_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory_service_app.laborder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="laborder",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratory_service_app.labtest",
            ),
        ),
    ]
