# Generated by Django 4.2.7 on 2025-05-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("session_type", models.CharField(default="general", max_length=50)),
                ("current_symptoms", models.JSONField(blank=True, default=dict)),
                ("preliminary_diagnosis", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possible_diseases", models.JSONField(default=list)),
                ("final_recommendations", models.TextField(blank=True)),
                ("confidence_level", models.CharField(default="low", max_length=20)),
                ("needs_urgent_care", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_service_app.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("common_age_groups", models.CharField(blank=True, max_length=100)),
                ("prevalence", models.CharField(default="common", max_length=20)),
                ("urgency_level", models.CharField(default="low", max_length=20)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("priority", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ResponseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("template_text", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("variables", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                (
                    "keywords",
                    models.TextField(
                        help_text="Từ khóa để nhận diện triệu chứng, phân cách bằng dấu phẩy"
                    ),
                ),
                ("severity_levels", models.JSONField(default=list)),
                ("is_critical", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportedSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("severity", models.CharField(default="mild", max_length=20)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("additional_details", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_service_app.diagnosissession",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_service_app.symptom",
                    ),
                ),
            ],
            options={
                "unique_together": {("diagnosis_session", "symptom")},
            },
        ),
        migrations.CreateModel(
            name="DiseaseSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("is_required", models.BooleanField(default=False)),
                ("frequency", models.CharField(default="common", max_length=20)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_service_app.disease",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_service_app.symptom",
                    ),
                ),
            ],
            options={
                "unique_together": {("disease", "symptom")},
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="symptoms",
            field=models.ManyToManyField(
                through="chatbot_service_app.DiseaseSymptom",
                to="chatbot_service_app.symptom",
            ),
        ),
        migrations.AddField(
            model_name="diagnosissession",
            name="reported_symptoms",
            field=models.ManyToManyField(
                through="chatbot_service_app.ReportedSymptom",
                to="chatbot_service_app.symptom",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("intent", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("message_type", models.CharField(default="general", max_length=50)),
                ("extracted_symptoms", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot_service_app.chatsession",
                    ),
                ),
            ],
        ),
    ]
